FROM colab-python39

# Force NumPY 2.x
RUN pip install pip==24.0
RUN pip install --no-cache-dir --prefer-binary numpy==2.0.2
RUN pip install --no-cache-dir --prefer-binary opencv-python==4.10.0.84
# See https://github.com/airctic/icevision/issues/1012
RUN pip install --no-cache-dir --prefer-binary opencv-python-headless==4.10.0.84
RUN pip install --no-cache-dir --prefer-binary sahi==0.10.8
RUN pip install --no-cache-dir --prefer-binary scikit-image==0.24.0
RUN pip install --no-cache-dir --prefer-binary fastcore==1.3.29
RUN pip install --no-cache-dir --prefer-binary fastai==2.5.6

## Other Experiments
## RUN pip install --no-cache-dir --prefer-binary pillow==0.8.4

# Install IceVision
# See https://raw.githubusercontent.com/airctic/icevision/master/icevision_install.sh
RUN mkdir -p .icevision
COPY icevision_install.sh .icevision/

RUN apt-get update -y
RUN apt-get install -y gdal-bin
## RUN bash .icevision/icevision_install.sh cpu
# RUN bash .icevision/icevision_install.sh cu11 master

# Expose port 8889 for Jupyter
EXPOSE 8889

# Start Jupyter notebook server
CMD ["jupyter", "notebook", "--allow-root", "--NotebookApp.allow_origin='https://colab.research.google.com'", "--NotebookApp.port_retries=0", "--NotebookApp.ip='0.0.0.0'", "--port=8889", "--no-browser"]