FROM python:3.9

ENV PYTHONUNBUFFERED=1

# Install necessary system dependencies
RUN apt-get update
RUN apt-get install -y \
    build-essential \
    curl \
    git \
    libsm6 \
    libxext6 \
    libxrender-dev \
    && rm -rf /var/lib/apt/lists/*

# Install pip, setuptools, wheel
RUN pip install --upgrade pip setuptools wheel

# Install Jupyter notebook
RUN pip install notebook==6.5.7

# Install Google Colab requirements
RUN pip install jupyter_http_over_ws
RUN jupyter serverextension enable jupyterlab/http-over-ws

# Expose port 8888 for Jupyter
EXPOSE 8888

# Start Jupyter notebook server
CMD ["jupyter", "notebook", "--allow-root", "--NotebookApp.allow_origin='https://colab.research.google.com'", "--NotebookApp.port_retries=0", "--NotebookApp.ip='0.0.0.0'", "--port=8888", "--no-browser"]